### ISSUE TITLE
Ability to create score excerpts [FEATURE]

### ISSUE THREAD

**Issue by johentsch** [johentsch/ms3#89]
The low-hanging fruit is to allow stripping all <Measure> tags that are not included in the desired excerpt. 

**ToDo**

- [x] implement the low-level `_MSCX_bs4.make_excerpt()` #90 
- [x] implement a high-level method such as `MSCX.store_excerpt()` with a user-friendly interface
- [x] more convenience methods, e.g.
  - [x] excerpts for all annotated phrases
  - [ ] excerpts based on a sequence of start measures

**Comment by johentsch** [comment]
addressed via #91
